-
  I set company logo and headers.
-
  !record {model: res.company, id: base.main_company}:
    rml_header: |
     <header>
          <pageTemplate>
              <frame id="first" x1="1.3cm" y1="3.0cm" height="21.7cm" width="19.0cm"/>
               <stylesheet>
                  <paraStyle name="main_footer"  fontName="DejaVu Sans" fontSize="8.0" alignment="CENTER"/>
                  <paraStyle name="main_header"  fontName="DejaVu Sans" fontSize="8.0" leading="10" alignment="LEFT" spaceBefore="0.0" spaceAfter="0.0"/>
               </stylesheet>
              <pageGraphics>
                  <!-- You Logo - Change X,Y,Width and Height -->
                  <image x="1.3cm" y="27.7cm" height="40.0" >[[ company.logo or removeParentNode('image') ]]</image>
                  <setFont name="DejaVu Sans" size="8"/>
                  <fill color="black"/>
                  <stroke color="black"/>
      
                  <!-- page header -->
                  <lines>1.3cm 27.7cm 20cm 27.7cm</lines>
                  <drawRightString x="20cm" y="27.8cm">[[ company.rml_header1 ]]</drawRightString>
                  <drawString x="1.3cm" y="27.3cm">[[ company.partner_id.name ]]</drawString>
                  <place x="1.3cm" y="25.3cm" height="1.8cm" width="15.0cm">
                      <para style="main_header">[[ display_address(company.partner_id) or  '' ]]</para>
                  </place>
                  <drawString x="1.3cm" y="25.0cm">Téléphone:</drawString>
                  <drawRightString x="7cm" y="25.0cm">[[ company.partner_id.phone or '' ]]</drawRightString>
                  <drawString x="1.3cm" y="24.6cm">Mail:</drawString>
                  <drawRightString x="7cm" y="24.6cm">[[ company.partner_id.email or '' ]]</drawRightString>
                  <lines>1.3cm 24.5cm 7cm 24.5cm</lines>
      
                  <!-- left margin -->
                  <rotate degrees="90"/>
                  <fill color="grey"/>
                  <drawString x="2.65cm" y="-0.4cm">generated by OpenERP.com</drawString>
                  <fill color="black"/>
                  <rotate degrees="-90"/>
      
                  <!--page bottom-->
                  <lines>1.2cm 2.65cm 19.9cm 2.65cm</lines>
                  <place x="1.3cm" y="0cm" height="2.55cm" width="19.0cm">
                      <para style="main_footer">[[ company.rml_footer ]]</para>
                      <para style="main_footer">Contact : [[ user.name ]] - Page: <pageNumber/></para>
                  </place>
              </pageGraphics>
          </pageTemplate>
      </header>
    rml_header2: |
      <header>
        <pageTemplate>
            <frame id="first" x1="28.0" y1="28.0" width="539" height="772"/>
            <pageGraphics>
                <fill color="black"/>
                <stroke color="black"/>
                <setFont name="DejaVu Sans" size="8"/>
                <drawString x="1.0cm" y="28.3cm"> [[ formatLang(time.strftime("%Y-%m-%d"), date=True) ]]  [[ time.strftime("%H:%M") ]]</drawString>
                <setFont name="DejaVu Sans Bold" size="10"/>
                <drawCentredString x="11.1cm" y="28.3cm">[[ company.partner_id.name ]]</drawCentredString>
                <stroke color="#000000"/>
                <lines>1.0cm 28.1cm 20.1cm 28.1cm</lines>
            </pageGraphics>
        </pageTemplate>
      </header>
    rml_header3: |
      <header>
        <pageTemplate>
            <frame id="first" x1="28.0" y1="28.0" width="786" height="525"/>
            <pageGraphics>
                <fill color="black"/>
                <stroke color="black"/>
                <setFont name="DejaVu Sans" size="8"/>
                <drawString x="25" y="555"> [[ formatLang(time.strftime("%Y-%m-%d"), date=True) ]]  [[ time.strftime("%H:%M") ]]</drawString>
                <setFont name="DejaVu Sans Bold" size="10"/>
                <drawCentredString x="440" y="555">[[ company.partner_id.name ]]</drawCentredString>
                <stroke color="#000000"/>
                <lines>25 550 818 550</lines>
            </pageGraphics>
        </pageTemplate>
      </header>
    rml_footer: "Les biens vendus (identifier ces biens) demeurent la propriété de l’entreprise jusqu'au paiement intégral du prix par l'acheteur.
                 La remise d'un titre créant une obligation de payer (une traite notamment) ne constitue pas le paiement. Le défaut de paiement pourra entraîner la revendication des biens. Ces dispositions ne font pas obstacle, à la livraison, au transfert à l'acheteur des risques de perte ou de détérioration des biens ou des dommages dont il serait la cause"

-
 Set company logos
-
  !python {model: res.company}: |
    self.set_logo (cr, uid, [ref('base.main_company')],  module="e3z_custom_config_ipbox", img_path="image",file_name="company_logo.png", field='logo', context=context)

-
  I set new headers for invoice
-

  !record {model: res.header, id: e3z_custom_config_ipbox.account_invoice_layout}:
    name : "header_invoice"
    internal : true
    rml_header: |
      <header>
              <pageTemplate>
                  <frame id="first" x1="1.3cm" y1="6.0cm" height="17.7cm" width="19.0cm"/>
                   <stylesheet>
                      <!-- Set here the default font to use for all <para> tags -->
                      <paraStyle name='Normal' fontName="DejaVu Sans"/>
                      <paraStyle name="main_footer" fontSize="8.0" alignment="CENTER"/>
                      <paraStyle name="main_footer_left" fontSize="8.0" alignment="LEFT"/>
                      <paraStyle name="main_header" fontSize="8.0" leading="10" alignment="LEFT" spaceBefore="0.0" spaceAfter="0.0"/>
                   </stylesheet>
                  <pageGraphics>
                      <!-- Set here the default font to use for all <drawString> tags -->
                      <setFont name="DejaVu Sans" size="8"/>
                      <!-- You Logo - Change X,Y,Width and Height -->
                      <image x="1.3cm" y="27.9cm" height="45.0" >[[ company.logo or removeParentNode('image') ]]</image>
                      <fill color="black"/>
                      <stroke color="black"/>
      
                      <!-- page header -->
                      <lines>1.3cm 27.7cm 20cm 27.7cm</lines>
                      <drawRightString x="20cm" y="27.8cm">[[ company.rml_header1 ]]</drawRightString>
                      <drawString x="1.3cm" y="27.3cm">[[ company.partner_id.name ]]</drawString>
                      <place x="1.3cm" y="25.3cm" height="1.8cm" width="15.0cm">
                          <para style="main_header">[[ display_address(company.partner_id) or  '' ]]</para>
                      </place>
                      <drawString x="1.3cm" y="25.0cm">Phone:</drawString>
                      <drawRightString x="7cm" y="25.0cm">[[ company.partner_id.phone or '' ]]</drawRightString>
                      <drawString x="1.3cm" y="24.6cm">Mail:</drawString>
                      <drawRightString x="7cm" y="24.6cm">[[ company.partner_id.email or '' ]]</drawRightString>
                      <lines>1.3cm 24.5cm 7cm 24.5cm</lines>

                      <!--page bottom-->
                      <lines>1.2cm 2.65cm 19.9cm 2.65cm</lines>
                      <place x="1.3cm" y="0cm" height="2.55cm" width="19.0cm">
                          <para style="main_footer">Contact : [[ user.name ]] - Page: <pageNumber/></para>
                          <para style="main_footer">
                            IPbox - 5 rue Claude Burdin- 63100 Clermont-Ferrand - Tél : [[ company.partner_id.phone or '' ]] – Fax : [[ company.partner_id.fax or '' ]]
                            SARL au capital de 129 000 eur
                            N°SIRET : [[ company.siret or '' ]] NAF : [[ company.ape or '' ]]  N° intracommunautaire : [[ company.vat or '' ]]
                          </para>
                      </place>
                  </pageGraphics>
              </pageTemplate>
          </header>

-
  I set new headers for shipping and sale
-
  !record {model: res.header, id: e3z_custom_config_ipbox.shipping_sale}:
    name : "header_shipping_sale"
    internal : true
    rml_header: |
      <header>
              <pageTemplate>
                   <frame id="first" x1="1.3cm" y1="6.0cm" height="17.7cm" width="19.0cm"/>
                   <stylesheet>
                      <!-- Set here the default font to use for all <para> tags -->
                      <paraStyle name='Normal' fontName="DejaVu Sans"/>
                      <paraStyle name="main_footer" fontSize="8.0" alignment="CENTER"/>
                      <paraStyle name="main_footer_left" fontSize="8.0" alignment="LEFT"/>
                      <paraStyle name="main_header" fontSize="8.0" leading="10" alignment="LEFT" spaceBefore="0.0" spaceAfter="0.0"/>
                   </stylesheet>
                  <pageGraphics>
                      <!-- Set here the default font to use for all <drawString> tags -->
                      <setFont name="DejaVu Sans" size="8"/>
                      <!-- You Logo - Change X,Y,Width and Height -->
                      <image x="1.3cm" y="27.9cm" height="45.0" >[[ company.logo or removeParentNode('image') ]]</image>
                      <fill color="black"/>
                      <stroke color="black"/>
          
                      <!-- page header -->
                      <lines>1.3cm 27.7cm 20cm 27.7cm</lines>
                      <drawString x="1.3cm" y="27.3cm">[[ company.partner_id.name ]]</drawString>
                      <place x="1.3cm" y="25.3cm" height="1.8cm" width="15.0cm">
                          <para style="main_header">[[ display_address(company.partner_id) or  '' ]]</para>
                      </place>
                      <drawString x="1.3cm" y="25.0cm">Téléphone:</drawString>
                      <drawRightString x="7cm" y="25.0cm">[[ company.partner_id.phone or '' ]]</drawRightString>
                      <drawString x="1.3cm" y="24.6cm">Mail:</drawString>
                      <drawRightString x="7cm" y="24.6cm">[[ company.partner_id.email or '' ]]</drawRightString>
                      <lines>1.3cm 24.5cm 7cm 24.5cm</lines>
          
                      <!-- left margin -->
                      <!--<rotate degrees="90"/>
                      <fill color="grey"/>
                      <drawString x="2.65cm" y="-0.4cm">generated by OpenERP.com</drawString>
                      <fill color="black"/>
                      <rotate degrees="-90"/>-->
          
                      <!--page bottom-->
                      <lines>1.0cm 4.5cm 20.0cm 4.5cm</lines>
                      <lines>1.0cm 4.5cm 1.0cm 3.0cm</lines>
                      <lines>20.0cm 4.5cm 20.0cm 3.0cm</lines>
                      <lines>1.0cm 3.0cm 20.0cm 3.0cm</lines>
                      <place x="1.3cm" y="2.20cm" height="2.55cm" width="19.0cm">
                        <para style="main_footer_left">
                          Clause de réserve de propriété :
                          En application de la loi 80-335 du 12 mai 1980, les marchandises livrées demeurent la propriété du vendeur jusqu'au complet règlement de leur prix.
                        </para>
                      </place>
                      <lines>1.2cm 2.65cm 19.9cm 2.65cm</lines>
                      <place x="1.3cm" y="0cm" height="2.55cm" width="19.0cm">
                          <para style="main_footer">[[ company.rml_footer ]]</para>
                          <para style="main_footer">Contact : [[ user.name ]] - Page: <pageNumber/></para>
                      </place>
                  </pageGraphics>
              </pageTemplate>
          </header>
